esphome:
  name: xmaslights
  platform: esp8266
  board: esp01_1m

  on_boot:
    # Toggle blink mode 7 times to get to the desired mode
    - delay: 1000ms
    - switch.turn_on: mode
    - delay: 500ms
    - switch.turn_on: mode
    - delay: 500ms
    - switch.turn_on: mode
    - delay: 500ms
    - switch.turn_on: mode
    - delay: 500ms
    - switch.turn_on: mode
    - delay: 500ms
    - switch.turn_on: mode
    - delay: 500ms
    - switch.turn_on: mode

wifi:
  ssid: $ssid
  password: $wifi_pw
  # Enable fallback access point when wifi is unavailable
  ap:
    ssid: "X-mas lights fallback AP"
    password: "blinkies"

captive_portal:

web_server:
  port: 80
  ota: false

ota:
  password: $ota_pw

# Enable Home Assistant API
api:
  password: $api_pw

logger:
  level: debug

switch:
  - platform: gpio
    pin:
      number: 2
      inverted: true
    id: mode
    name: "X-mas lights"
    # Emulate push button by auto switching off
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: mode
    
